import { Link } from "react-router-dom";
import { Trash2 } from "lucide-react";
import ProductArt from "../components/ProductArt";
import QuantitySelector from "../components/QuantitySelector";
import { useCart } from "../contexts/CartContext";
import { formatPKR } from "../utils/format";
export default function Cart() {
  const { items, subtotal, deliveryFee, total, removeItem, updateQuantity } = useCart();
  if (!items.length) return <div className="container-page py-12"><div className="card-soft p-10 text-center"><p className="text-6xl">🛒</p><h1 className="mt-4 font-display text-4xl font-extrabold text-cocoa">Your cart is empty</h1><p className="mt-2 text-sm font-semibold text-cocoa/55">Add some cozy Cub Club products first.</p><Link to="/shop" className="btn-primary mt-6">Start shopping</Link></div></div>;
  return <div className="container-page py-8 sm:py-12"><h1 className="font-display text-5xl font-extrabold text-cocoa">Your Cart</h1><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_380px]"><div className="grid gap-4">{items.map((item) => <div key={item.product.id} className="card-soft grid grid-cols-[96px_1fr] gap-4 p-3 sm:grid-cols-[130px_1fr]"><div className="aspect-square overflow-hidden rounded-3xl bg-blush"><ProductArt imageUrl={item.product.main_image_url} title={item.product.name} /></div><div className="flex min-w-0 flex-col justify-between py-2 pr-2"><div><h2 className="font-display text-xl font-bold leading-tight text-cocoa">{item.product.name}</h2><p className="mt-1 text-sm font-bold text-cocoa/45">{item.product.size} · {item.product.color}</p><p className="mt-2 text-base font-extrabold text-cocoa">{formatPKR(item.product.price)}</p></div><div className="mt-4 flex items-center justify-between gap-3"><QuantitySelector value={item.quantity} max={Math.max(item.product.stock_quantity, 1)} onChange={(qty) => updateQuantity(item.product.id, qty)} /><button onClick={() => removeItem(item.product.id)} className="flex h-10 w-10 items-center justify-center rounded-full bg-white text-red-500 shadow-sm ring-1 ring-cocoa/5"><Trash2 size={17} /></button></div></div></div>)}</div><aside className="card-soft h-fit p-6 lg:sticky lg:top-28"><h2 className="font-display text-3xl font-bold text-cocoa">Order Summary</h2><div className="mt-5 grid gap-3 text-sm font-bold text-cocoa/65"><div className="flex justify-between"><span>Subtotal</span><span>{formatPKR(subtotal)}</span></div><div className="flex justify-between"><span>Delivery</span><span>{deliveryFee ? formatPKR(deliveryFee) : "Free"}</span></div><div className="flex justify-between border-t border-cocoa/10 pt-3 text-lg font-extrabold text-cocoa"><span>Total</span><span>{formatPKR(total)}</span></div></div><Link to="/checkout" className="btn-primary mt-6 w-full py-4">Checkout with COD</Link><Link to="/shop" className="btn-secondary mt-3 w-full">Continue shopping</Link></aside></div></div>;
}
