import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { useAuth } from "../contexts/AuthContext";
import { useCart } from "../contexts/CartContext";
import { createOrder } from "../lib/storeApi";
import { formatPKR } from "../utils/format";

export default function Checkout() {
  const { items, subtotal, deliveryFee, total, clearCart } = useCart();
  const { user, profile } = useAuth();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ customerName: "", customerPhone: "", customerEmail: "", city: "", deliveryAddress: "", notes: "" });
  useEffect(() => { setForm((c) => ({ ...c, customerName: c.customerName || profile?.full_name || "", customerPhone: c.customerPhone || profile?.phone || "", customerEmail: c.customerEmail || user?.email || "", city: c.city || profile?.city || "", deliveryAddress: c.deliveryAddress || profile?.address || "" })); }, [profile, user]);
  if (!items.length) return <div className="container-page py-12"><div className="card-soft p-10 text-center"><h1 className="font-display text-4xl font-extrabold text-cocoa">Your cart is empty</h1><Link to="/shop" className="btn-primary mt-6">Shop now</Link></div></div>;
  async function handleSubmit(event: FormEvent) { event.preventDefault(); setLoading(true); try { for (const item of items) { if (item.quantity > item.product.stock_quantity && item.product.stock_quantity > 0) throw new Error(`${item.product.name} does not have enough stock.`); } const order = await createOrder({ userId: user?.id ?? null, customerName: form.customerName, customerPhone: form.customerPhone, customerEmail: form.customerEmail, city: form.city, deliveryAddress: form.deliveryAddress, notes: form.notes, items, deliveryFee }); clearCart(); toast.success("Order placed successfully"); navigate(`/order-success/${order.id}`); } catch (error: any) { toast.error(error.message || "Could not place order"); } finally { setLoading(false); } }
  return <div className="container-page py-8 sm:py-12"><div className="mb-8"><p className="label-soft">Cash on delivery</p><h1 className="font-display text-5xl font-extrabold text-cocoa">Checkout</h1><p className="mt-2 text-sm font-semibold text-cocoa/60">Place the order now. Cub Club can confirm by phone before delivery.</p></div><form onSubmit={handleSubmit} className="grid gap-6 lg:grid-cols-[1fr_380px]"><div className="card-soft p-5 sm:p-8"><h2 className="font-display text-3xl font-bold text-cocoa">Delivery details</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Full name" required value={form.customerName} onChange={(v) => setForm({ ...form, customerName: v })} /><Field label="Phone number" required value={form.customerPhone} onChange={(v) => setForm({ ...form, customerPhone: v })} placeholder="03xx xxxxxxx" /><Field label="Email optional" type="email" value={form.customerEmail} onChange={(v) => setForm({ ...form, customerEmail: v })} /><Field label="City" required value={form.city} onChange={(v) => setForm({ ...form, city: v })} /><div className="sm:col-span-2"><label className="label-soft">Full delivery address *</label><textarea required rows={4} value={form.deliveryAddress} onChange={(e) => setForm({ ...form, deliveryAddress: e.target.value })} className="input-soft resize-none" placeholder="House number, street, area, city..." /></div><div className="sm:col-span-2"><label className="label-soft">Notes optional</label><textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="input-soft resize-none" placeholder="Any delivery note..." /></div></div></div><aside className="card-soft h-fit p-6 lg:sticky lg:top-28"><h2 className="font-display text-3xl font-bold text-cocoa">Your order</h2><div className="mt-5 grid gap-4">{items.map((item) => <div key={item.product.id} className="flex justify-between gap-3 text-sm font-bold text-cocoa/65"><span>{item.product.name} × {item.quantity}</span><span>{formatPKR(item.product.price * item.quantity)}</span></div>)}</div><div className="mt-5 grid gap-3 border-t border-cocoa/10 pt-5 text-sm font-bold text-cocoa/65"><div className="flex justify-between"><span>Subtotal</span><span>{formatPKR(subtotal)}</span></div><div className="flex justify-between"><span>Delivery</span><span>{deliveryFee ? formatPKR(deliveryFee) : "Free"}</span></div><div className="flex justify-between text-lg font-extrabold text-cocoa"><span>Total</span><span>{formatPKR(total)}</span></div></div><div className="mt-5 rounded-3xl bg-butter/50 p-4 text-sm font-bold leading-6 text-cocoa/70">Payment method: Cash on Delivery only.</div><button disabled={loading} className="btn-primary mt-5 w-full py-4">{loading ? "Placing order..." : "Place COD order"}</button></aside></form></div>;
}
function Field({ label, value, onChange, required, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string; placeholder?: string }) { return <div><label className="label-soft">{label}{required ? " *" : ""}</label><input required={required} type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="input-soft" /></div>; }
