import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ShoppingBag } from "lucide-react";
import ProductArt from "../components/ProductArt";
import QuantitySelector from "../components/QuantitySelector";
import { useCart } from "../contexts/CartContext";
import { fetchProductBySlug, fetchProductImages } from "../lib/storeApi";
import { Product, ProductImage } from "../types";
import { formatPKR } from "../utils/format";
export default function ProductDetail() {
  const { slug } = useParams(); const [product, setProduct] = useState<Product | null>(null); const [images, setImages] = useState<ProductImage[]>([]); const [loading, setLoading] = useState(true); const [quantity, setQuantity] = useState(1); const [selectedImage, setSelectedImage] = useState<string | null>(null); const { addItem } = useCart();
  useEffect(() => { if (!slug) return; setLoading(true); fetchProductBySlug(slug).then(async (p) => { setProduct(p); if (p?.id && !p.id.startsWith("demo-")) { const imgs = await fetchProductImages(p.id); setImages(imgs); setSelectedImage(p.main_image_url ?? imgs[0]?.image_url ?? null); } else setSelectedImage(p?.main_image_url ?? null); }).finally(() => setLoading(false)); }, [slug]);
  const gallery = useMemo(() => Array.from(new Set([product?.main_image_url, ...images.map((i) => i.image_url)].filter(Boolean) as string[])), [images, product]);
  if (loading) return <div className="container-page py-12"><div className="h-[620px] animate-pulse rounded-[3rem] bg-white/70 shadow-card" /></div>;
  if (!product) return <div className="container-page py-12"><div className="card-soft p-10 text-center"><p className="text-5xl">🧸</p><h1 className="mt-4 font-display text-3xl font-bold text-cocoa">Product not found</h1><Link to="/shop" className="btn-primary mt-6">Back to shop</Link></div></div>;
  const isOut = product.stock_quantity <= 0;
  return <div className="container-page py-8 sm:py-12"><Link to="/shop" className="mb-6 inline-flex items-center gap-2 text-sm font-extrabold text-cocoa/65 hover:text-cocoa"><ArrowLeft size={17} /> Back to shop</Link><div className="grid gap-8 lg:grid-cols-[1fr_0.9fr]"><div><div className="aspect-square overflow-hidden bg-white p-3 shadow-store ring-1 ring-black/5"><ProductArt imageUrl={selectedImage} title={product.name} categoryName={product.categories?.name} variant="detail" /></div>{gallery.length > 1 ? <div className="mt-4 flex gap-3 overflow-x-auto pb-2 no-scrollbar">{gallery.map((image) => <button key={image} onClick={() => setSelectedImage(image)} className="h-20 w-20 shrink-0 overflow-hidden rounded-2xl bg-white p-1 shadow-sm ring-1 ring-cocoa/10"><img src={image} alt={product.name} className="h-full w-full rounded-xl object-cover" /></button>)}</div> : null}</div><div className="lg:sticky lg:top-28 lg:self-start"><div className="bg-white p-6 shadow-store ring-1 ring-black/5 sm:p-8"><p className="label-soft">{product.categories?.name ?? "Cub Club"}</p><h1 className="text-5xl font-black uppercase leading-none tracking-[-0.04em] text-ink">{product.name}</h1><p className="mt-4 text-base font-semibold leading-8 text-cocoa/60">{product.description ?? product.short_description}</p><div className="mt-6 flex items-end gap-3"><span className="text-4xl font-black text-red-600">{formatPKR(product.price)}</span>{product.compare_at_price ? <span className="pb-1 text-lg font-bold text-cocoa/35 line-through">{formatPKR(product.compare_at_price)}</span> : null}</div><div className="mt-6 grid grid-cols-2 gap-3"><Info label="Size" value={product.size} /><Info label="Color" value={product.color} /><Info label="Age" value={product.age_range} /><Info label="Material" value={product.material} /></div><div className="mt-6 bg-cream p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-extrabold text-cocoa">Quantity</p><p className="mt-1 text-xs font-bold text-cocoa/45">{isOut ? "Currently out of stock" : `${product.stock_quantity} available`}</p></div><QuantitySelector value={quantity} max={Math.max(product.stock_quantity, 1)} onChange={(v) => setQuantity(Math.max(1, v))} /></div></div><button disabled={isOut} onClick={() => addItem(product, quantity)} className="btn-primary mt-6 w-full py-4 text-base disabled:bg-cocoa/25"><ShoppingBag className="mr-2" size={20} />{isOut ? "Out of stock" : "Add to cart"}</button><div className="mt-5 bg-paper p-4 text-sm font-medium leading-7 text-ink/55 ring-1 ring-black/5">Cash on delivery available. Cub Club will contact you after checkout to confirm delivery details.</div></div></div></div></div>;
}
function Info({ label, value }: { label: string; value?: string | null }) { return <div className="bg-paper p-4 ring-1 ring-black/5"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-cocoa/40">{label}</p><p className="mt-1 text-sm font-extrabold text-cocoa">{value || "—"}</p></div>; }
